# Generated by Django 4.0.3 on 2023-10-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_answer_author_question_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='create_date',
            new_name='create_data',
        ),
    ]
