# Generated by Django 4.0.3 on 2023-10-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_rename_create_date_answer_create_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
