# Generated by Django 4.0.3 on 2023-10-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_answer_modify_date_question_modify_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='create_data',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='modify_data',
            new_name='modify_date',
        ),
    ]
